
some_function :: (a: u8, b: u16, c: u32, d: int) -> int {
	return cast(int)a + cast(int)b + cast(int)c + d;
}

main :: () -> int {


	if 1 {
		return 0;
	}

	while true {
		return variable_which_does_not_exist;
	} 
	
	do_not_finish_statement_properly

	s: int = 10;
	if 6 > 0 == true {
		i: int = 10;
		s;	
	}
		
	i;

	value: string = 9;
	
	other_value: u8 = "string" + 89;

	some_other_value: int = 8***;

	8*8;

	8+

	yo: string = "yo";


	yo = some_function(1, 2, 3, 4, 3);
	


	return 0;
}
